### ISSUE TITLE
TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by nilsdenon** [getshifter/shifter-headless-nextjs-typescript#1]
Here are the steps I followed:
1. cloned the repo and installed the packages
2. created a .env file with wp-api URL
3. npm run dev
![image](https://user-images.githubusercontent.com/1893234/105557419-7f336f00-5d0c-11eb-8d31-5606916dd1c6.png)

**Comment by emaildano** [comment]
Hey @nilsdenon, we've refactored this repo if you're interested. That issue reported many moons ago was resolved. Happy coding! 👋🏻
